# This file is generated by Anlogic Timing Wizard. 08 08 2022

#Created Clock
create_clock -name base_clk -period 41.66 -waveform {0 20.83} [get_ports {base_clk}]

#Created Generated Clock
create_generated_clock  -add -name fast_clk -source [get_ports {base_clk}] -master_clock base_clk -multiply_by 5 [get_nets {fast_clk}]

